In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## Define the vocabulary size
voc_size=10000

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2674, 6759, 5942, 2472],
 [2674, 6759, 5942, 8545],
 [2674, 910, 5942, 4472],
 [2050, 9441, 8644, 4206, 1963],
 [2050, 9441, 8644, 4206, 2414],
 [666, 2674, 4784, 5942, 5566],
 [3576, 9193, 8110, 4206]]

In [13]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2674 6759 5942 2472]
 [   0    0    0    0 2674 6759 5942 8545]
 [   0    0    0    0 2674  910 5942 4472]
 [   0    0    0 2050 9441 8644 4206 1963]
 [   0    0    0 2050 9441 8644 4206 2414]
 [   0    0    0  666 2674 4784 5942 5566]
 [   0    0    0    0 3576 9193 8110 4206]]


In [16]:
## feature representation
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Nikki\.conda\envs\testingopenai\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 611ms/step


array([[[-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.00360097, -0.02681407,  0.03202022, -0.02316632,
         -0.03673211,  0.00373157, -0.03775731,  0.04412023,
          0.00317441, -0.00501064],
        [ 0.0071321 ,  0.0389354 ,  0.03655228, -0.04886587,
          0.03581694,  0.02454164, -0.02922511,  0.03251357,
         -0.03296321,  0.02590084],
        [ 0.01843477,  0.02431024,  0.04482784,  0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 2674, 6759, 5942, 2472])

In [24]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step


array([[[-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.03038211, -0.03360143,  0.00494833, -0.01184661,
         -0.00690312,  0.02906727,  0.01861179,  0.04471389,
         -0.00821536, -0.01012105],
        [-0.00360097, -0.02681407,  0.03202022, -0.02316632,
         -0.03673211,  0.00373157, -0.03775731,  0.04412023,
          0.00317441, -0.00501064],
        [ 0.0071321 ,  0.0389354 ,  0.03655228, -0.04886587,
          0.03581694,  0.02454164, -0.02922511,  0.03251357,
         -0.03296321,  0.02590084],
        [ 0.01843477,  0.02431024,  0.04482784,  0.0